# fly.toml app configuration file generated for patient-bird-8511 on 2023-11-01T20:07:31-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "patient-bird-8511"
primary_region = "atl"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
